# Generated by Django 4.0.4 on 2022-05-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTA', '0008_delete_noserinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='file',
            field=models.FileField(default='abc', upload_to='media/', verbose_name='文件地址'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='file_name',
            field=models.TextField(default='abc', max_length=64),
        ),
    ]
