# Generated by Django 4.0.4 on 2022-05-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTA', '0009_userinfo_file_userinfo_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='file',
            field=models.FileField(default='null', upload_to='media/', verbose_name='文件地址'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='file_name',
            field=models.TextField(default='null', max_length=64),
        ),
    ]
