# Generated by Django 4.0.4 on 2022-05-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTA', '0010_alter_userinfo_file_alter_userinfo_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='file',
            field=models.FileField(default='null', upload_to='files/', verbose_name='文件地址'),
        ),
    ]
