# Generated by Django 4.0.4 on 2022-05-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTA', '0002_rename_repoter_userinfo_reporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='reporter',
            field=models.CharField(max_length=128),
        ),
    ]
