# Generated by Django 4.0.4 on 2022-05-11 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTA', '0005_userinfo_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
