# Generated by Django 4.0.4 on 2022-05-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=64)),
                ('device', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=64)),
                ('repoter', models.CharField(max_length=64)),
            ],
        ),
    ]
