# Generated by Django 4.0.4 on 2022-05-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTA', '0003_alter_userinfo_reporter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='date',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='device',
            field=models.TextField(max_length=64),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.TextField(max_length=64),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='reporter',
            field=models.TextField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='version',
            field=models.TextField(max_length=64),
        ),
    ]
