# Generated by Django 4.0.4 on 2022-05-11 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('OTA', '0004_remove_userinfo_date_alter_userinfo_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
