# Generated by Django 4.0.4 on 2022-05-11 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTA', '0007_noserinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='noserInfo',
        ),
    ]
